### PR TITLE
SCSS files renamed because of deprecation warning

### PR DESCRIPTION
**Pull request by aypn0s**

### CODE REVIEW

**Comment by railsdevmatt** [comment]
@the-teacher - where is this at?

**Comment by the-teacher** [comment]
@railsdevmatt hello! Sorry, I cant understand what do you mean. Could you explain?

**Comment by railsdevmatt** [comment]
@the-teacher - I am using release 2.5.0 which does not have the `.css.scss` to `.scss` conversion and I run into deprecation warnings like
```ruby
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/sortable_tree.css.scss to /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/sortable_tree.scss. (called from _app_views_layouts_application_html_haml__382310849341476857_70125746854620 at /Users/matt/Sites/project/app/views/layouts/application.html.haml:20)
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/nested_options.css.scss to /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/nested_options.scss. (called from _app_views_layouts_application_html_haml__382310849341476857_70125746854620 at /Users/matt/Sites/project/app/views/layouts/application.html.haml:20)
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/sortable_tree.css.scss to /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/sortable_tree.scss. (called from _app_views_layouts_application_html_haml__382310849341476857_70125746854620 at /Users/matt/Sites/project/app/views/layouts/application.html.haml:20)
DEPRECATION WARNING: Extra .css in SCSS file is unnecessary. Rename /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/nested_options.css.scss to /Users/matt/.rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/the_sortable_tree-2.5.0/app/assets/stylesheets/nested_options.scss. (called from _app_views_layouts_application_html_haml__382310849341476857_70125746854620 at /Users/matt/Sites/project/app/views/layouts/application.html.haml:20)
```
Merging this PR into master and cutting a new release will solve that

**Comment by the-teacher** [comment]
@railsdevmatt doh. Looks ugly after years of rails conventions about CSS naming and so on. But ok. It looks like common practice for now. Let it be. Merge.

**Pull request merged**
