### PR TITLE
Rails 5.1 compatibility

### PR DESCRIPTION
**Pull request by vadimstroganov**
`render(nothing: true)` does not work in Rails Version >= 5.1
`render(nothing: true)` is replaced by the custom handler 'head_respond', which checks the version of Rails and uses the required answer variant (`head` or `render(nothing: true)`).

### CODE REVIEW

**Comment by uuushiro** [comment]
When is it merged?

**Comment by seanfcarroll** [comment]
+1

**Comment by araslanov-e** [comment]
+1
When is it merged?

**Comment by seanfcarroll** [comment]
Rails 5.2 will be released soon.

**Comment by the-teacher** [comment]
@seanfcarroll @araslanov-e @perlmunger @uuushiro @vadimstroganov I closed my eyes and just pressed the merge button. In case if you have any issue, please, send a PR.
I'll try to update the gem on rubygems ASAP.

**Comment by seanfcarroll** [comment]
Hi @the-teacher, I like your style. Perhaps it would help if members of the community using this gem (eg: like myself), could write some tests. Then, as an open source project, you could have a free CI such as Travis.

Thanks for the great gem!

**Comment by araslanov-e** [comment]
@the-teacher напиши, пожалуйста, когда гем обновишь на rubygems, чтобы сразу обновиться

**Comment by the-teacher** [comment]
@araslanov-e https://rubygems.org/gems/the_sortable_tree/versions/2.7.0

**Comment by araslanov-e** [comment]
@the-teacher thanks!

**Comment by araslanov-e** [comment]
@the-teacher у тебя REAMDE не соответсвует содержимому. Стили и js иначе стали подключаться и именоваться

**Comment by araslanov-e** [comment]
@the-teacher ты можешь выпустить версию 2.6.2 с поддержкой Rails 5?

**Comment by araslanov-e** [comment]
))) забыли сделать include DefineDeprecatedMethods

**Comment by araslanov-e** [comment]
@the-teacher https://github.com/araslanov-e/the_sortable_tree/tree/v2.6.2. Создай ветку, типо v_2_6, я в неё пулл реквест сделаю

**Pull request merged**
